### ISSUE TITLE
Wouldn't update

### ISSUE THREAD

**Issue by TeresaMcEachern** [gambitph/Stackable#105]
When I clicked for an update, I got an error message that I needed to buy Premium again.

I tried putting my licence key in again, but got an error message that I already used it on another install. 

(**_Image removed_**)

I only have one site, DelightfulWoman.com. Don't understand why this changed upon update. 

Thanks!
Teresa McEachern

**Comment by TeresaMcEachern** [comment]
Maybe I do know! The site was messed up by a plugin I installed and I had to start again. That may be why it thinks there is another install. But it was the same domain name.

**Comment by Gambit-Alyssa** [comment]
Hi Teresa! 😊 We got your mail via support and sent you a reply.
Since we deactivated the license in our end, activating it again should work now.

**Comment by TeresaMcEachern** [comment]
Hello,
I am still getting the same error message. See attached. Thanks!

**Comment by bfintal** [comment]
Hi @TeresaMcEachern 

I removed the image you posted since it displayed your license key :)

@Gambit-Alyssa should have emailed you with a new one, since someone else might have seen it and used it while it was available. Please use that one instead.
