### ISSUE TITLE
Posts Block: Category doesn't show up

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#107]
**Describe the bug**
Posts Block categories doesn't show up in the dropdown

**To Reproduce**
1. Create a Post, add a category in it
2. In a new page, add a Posts Block and pick a category
3. Category dropdown doesn't have anything other than All

**Expected behavior**
Additional categories should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/11436202/57918319-1bb33600-78c9-11e9-9537-b84386632f25.png)

**Comment by bfintal** [comment]
Fixed by 1647f2789394f7446e31dda8842ebae14a21d549

**Comment by DarioBF** [comment]
Sorry for reopening this bug, but still happening when a custom rewrite rule applies to categories.

**To reproduce:
Apply a rewrite rule, like this:
`add_action('init', 'abn_parent_category_slug_removal_hack', 0);
/** Remove parent categories slug from URLS hacking the register_taxonomy declaration with a false hierarchical rewrite */
if( !function_exists('abn_parent_category_slug_removal_hack') ):
function abn_parent_category_slug_removal_hack()
{
	$rewrite = array(
		'hierarchical' => false,
		'slug'         => get_option('category_base') ? get_option('category_base') : 'category',
		'with_front'   => false
	);

	register_taxonomy('category', 'post', array(
		'hierarchical'          => true,
 		'update_count_callback' => '_update_post_term_count',
		'query_var'             => 'category_name',
		'rewrite'               => did_action('init') ? $rewrite : false,
		'public'                => true,
		'show_ui'               => true,
		'_builtin'              => true,
		'show_in_rest'			=> true
	));
}
endif;`

Then, try to select a category filter in Posts Block's selector. Only appears the option "All"

**Expected behavior**
Additional categories should appear

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Firefox Developers edition
 - Browser Version: 68.0b1 (64-bit)
